apiVersion: v1
kind: Service
metadata: 
  name: myapp-service
  labels: 
    app: myapp
    tier: front-end
spec: 
  type: NodePort
  ports: 
    - 
      protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30008
  selector: 
    app: myapp
    tier: front-end
